name: "CUBU"
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
defaults:
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      site.data.author: default